import React, { useState, useRef, useEffect } from 'react';
import { useAuth } from './lib/auth';
import { UploadCloud, FileText, ShieldCheck, AlertTriangle, Activity, CheckCircle2, Loader2, Send, ShieldAlert, BookOpen, User } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

// Mock Data for Analytics
const faithfulnessData = [
  { day: 'Mon', score: 92 }, { day: 'Tue', score: 88 }, { day: 'Wed', score: 95 },
  { day: 'Thu', score: 82 }, { day: 'Fri', score: 97 }, { day: 'Sat', score: 99 }, { day: 'Sun', score: 96 },
];

export default function Dashboard() {
  const { user, logout } = useAuth();
  const [activeTab, setActiveTab] = useState('query'); // Defaulting to the new Query tab
  const [uploadState, setUploadState] = useState('idle'); 
  
  // Chat State
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);
  const [chatHistory, setChatHistory] = useState([
    {
      role: 'assistant',
      content: 'Welcome to MediRAG. I am your verified clinical intelligence assistant. My responses are fact-checked against your uploaded records. How can I help you today?',
      score: 1.0,
      citations: []
    }
  ]);

  // Auto-scroll chat to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatHistory, isTyping]);

  const handleSimulatedUpload = () => {
    setUploadState('uploading');
    setTimeout(() => setUploadState('extracting'), 1500);
    setTimeout(() => setUploadState('vectorizing'), 3000);
    setTimeout(() => setUploadState('done'), 5000);
    setTimeout(() => setUploadState('idle'), 7000);
  };

  const handleSendMessage = (e) => {
    e.preventDefault();
    if (!inputValue.trim()) return;

    const newUserMsg = { role: 'user', content: inputValue };
    setChatHistory(prev => [...prev, newUserMsg]);
    setInputValue('');
    setIsTyping(true);

    // Simulate Dual-Agent Verification Pipeline for the Demo
    setTimeout(() => {
      const isAllergyQuery = newUserMsg.content.toLowerCase().includes('allergy') || newUserMsg.content.toLowerCase().includes('penicillin');
      
      let aiResponse = {};
      if (isAllergyQuery) {
        // SUCCESS STATE (Green)
        aiResponse = {
          role: 'assistant',
          content: "Based on the uploaded records, the patient has a severe documented allergy to penicillin. A reaction in 2018 resulted in hives and shortness of breath. Recommend alternative antibiotic pathways.",
          score: 0.94,
          citations: ["Patient_History_2018.pdf (Page 3)", "Allergy_Panel_Lab.pdf (Page 1)"]
        };
      } else {
        // FALLBACK STATE (Peach)
        aiResponse = {
          role: 'assistant',
          content: "The primary model attempted to state a fact not explicitly covered in the context. The Critic Agent rejected the response due to a low faithfulness score. This answer was regenerated by the Llama-3 safety fallback using strict clinical boundaries: No additional diagnoses found in the current documents.",
          score: 0.42,
          citations: ["System_Audit_Log (Fallback Triggered)"]
        };
      }

      setChatHistory(prev => [...prev, aiResponse]);
      setIsTyping(false);
    }, 2500);
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Top Navigation */}
      <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="h-8 w-8 bg-primary rounded-lg flex items-center justify-center shadow-sm">
              <ShieldCheck className="h-5 w-5 text-white" />
            </div>
            <h1 className="text-xl font-bold text-gray-900 dark:text-white tracking-tight">MediRAG</h1>
          </div>
          <div className="flex items-center space-x-4">
            <span className="text-sm text-gray-500 font-medium">Dr. {user?.email?.split('@')[0] || 'Clinician'}</span>
            <button onClick={logout} className="text-sm font-medium text-gray-600 hover:text-primary transition-colors">
              Sign out
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Tab Navigation */}
        <div className="flex space-x-1 bg-gray-100 dark:bg-gray-800 p-1 rounded-xl w-fit mb-8 shadow-inner border border-gray-200 dark:border-gray-700">
          <button onClick={() => setActiveTab('query')} className={`px-5 py-2.5 rounded-lg text-sm font-semibold transition-all ${activeTab === 'query' ? 'bg-white dark:bg-gray-700 text-primary shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}>
            Clinical Agent
          </button>
          <button onClick={() => setActiveTab('documents')} className={`px-5 py-2.5 rounded-lg text-sm font-semibold transition-all ${activeTab === 'documents' ? 'bg-white dark:bg-gray-700 text-primary shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}>
            Patient Records
          </button>
          <button onClick={() => setActiveTab('analytics')} className={`px-5 py-2.5 rounded-lg text-sm font-semibold transition-all ${activeTab === 'analytics' ? 'bg-white dark:bg-gray-700 text-primary shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}>
            Analytics
          </button>
        </div>

        {/* --- CLINICAL AGENT TAB (Ad-Hoc Query) --- */}
        {activeTab === 'query' && (
          <div className="flex flex-col h-[650px] bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 animate-in fade-in slide-in-from-bottom-4 duration-500 overflow-hidden">
            
            {/* Chat Header */}
            <div className="px-6 py-4 border-b border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-800/50 flex justify-between items-center">
              <div className="flex items-center space-x-3">
                <div className="relative">
                  <div className="h-10 w-10 bg-primary/10 rounded-full flex items-center justify-center">
                    <ShieldCheck className="h-6 w-6 text-primary" />
                  </div>
                  <div className="absolute bottom-0 right-0 h-3 w-3 bg-green-500 border-2 border-white rounded-full"></div>
                </div>
                <div>
                  <h3 className="text-sm font-bold text-gray-900 dark:text-white">MediRAG Verifier</h3>
                  <p className="text-xs text-gray-500">Dual-Agent Pipeline Active</p>
                </div>
              </div>
              <span className="inline-flex items-center px-2.5 py-1 rounded-md text-xs font-bold bg-primary/10 text-primary border border-primary/20">
                Gemini 3.1 Pro (Primary)
              </span>
            </div>

            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-gray-50/30 dark:bg-gray-900/30">
              {chatHistory.map((msg, idx) => (
                <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  {msg.role === 'assistant' && (
                    <div className="h-8 w-8 bg-primary rounded-lg flex items-center justify-center shrink-0 mt-1 shadow-sm mr-3">
                      <ShieldCheck className="h-5 w-5 text-white" />
                    </div>
                  )}
                  
                  <div className="flex flex-col space-y-2 max-w-[80%]">
                    <div className={`p-4 text-sm leading-relaxed shadow-sm ${
                      msg.role === 'user' 
                        ? 'bg-primary text-white rounded-2xl rounded-tr-none' 
                        : 'bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 text-gray-800 dark:text-gray-200 rounded-2xl rounded-tl-none'
                    }`}>
                      {msg.content}
                    </div>
                    
                    {/* Verification & Citations Footer */}
                    {msg.role === 'assistant' && msg.score && (
                      <div className="flex flex-wrap gap-2 items-center mt-1">
                        {msg.score >= 0.6 ? (
                          <span className="inline-flex items-center px-2 py-1 rounded-md text-[10px] font-bold bg-green-50 text-green-700 border border-green-200">
                            <CheckCircle2 className="w-3 h-3 mr-1" /> Verified (Score: {msg.score})
                          </span>
                        ) : (
                          <span className="inline-flex items-center px-2 py-1 rounded-md text-[10px] font-bold bg-secondary/20 text-secondary-foreground border border-secondary/30">
                            <ShieldAlert className="w-3 h-3 mr-1 text-secondary-foreground" /> Regenerated (Safety Fallback)
                          </span>
                        )}
                        
                        {msg.citations?.map((cite, i) => (
                          <button key={i} className="inline-flex items-center px-2 py-1 rounded-md text-[10px] font-medium bg-gray-100 text-gray-600 hover:bg-gray-200 border border-gray-200 transition-colors cursor-pointer">
                            <BookOpen className="w-3 h-3 mr-1" /> {cite}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>

                  {msg.role === 'user' && (
                    <div className="h-8 w-8 bg-gray-200 dark:bg-gray-700 rounded-full flex items-center justify-center shrink-0 mt-1 ml-3">
                      <User className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    </div>
                  )}
                </div>
              ))}
              
              {/* Typing Indicator */}
              {isTyping && (
                <div className="flex items-start space-x-3">
                  <div className="h-8 w-8 bg-primary rounded-lg flex items-center justify-center shrink-0 mt-1 shadow-sm">
                    <Loader2 className="h-5 w-5 text-white animate-spin" />
                  </div>
                  <div className="bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 p-4 rounded-2xl rounded-tl-none shadow-sm flex space-x-2 items-center">
                     <div className="w-2 h-2 bg-primary/40 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                     <div className="w-2 h-2 bg-primary/60 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                     <div className="w-2 h-2 bg-primary/80 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                     <span className="text-xs text-gray-400 ml-2 font-medium tracking-wide uppercase">Searching Vectors...</span>
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input Area */}
            <div className="p-4 bg-white dark:bg-gray-800 border-t border-gray-100 dark:border-gray-700">
              <form onSubmit={handleSendMessage} className="relative flex items-center">
                <input
                  type="text"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  placeholder="Ask a clinical question about the patient records..."
                  disabled={isTyping}
                  className="w-full pl-5 pr-14 py-4 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-shadow disabled:opacity-50"
                />
                <button
                  type="submit"
                  disabled={!inputValue.trim() || isTyping}
                  className="absolute right-2 p-2 bg-primary text-white rounded-lg hover:bg-primary/90 disabled:opacity-50 disabled:hover:bg-primary transition-colors shadow-sm"
                >
                  <Send className="w-5 h-5" />
                </button>
              </form>
              <div className="mt-2 text-center">
                <p className="text-[10px] text-gray-400 font-medium">Responses are fact-checked by the Critic Agent. Medical decisions should be independently verified.</p>
              </div>
            </div>
          </div>
        )}

        {/* --- DOCUMENTS TAB --- */}
        {activeTab === 'documents' && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className={`relative border-2 border-dashed rounded-2xl p-12 transition-all duration-300 flex flex-col items-center justify-center
              ${uploadState === 'idle' ? 'border-gray-300 hover:border-primary bg-white hover:bg-primary/5 dark:bg-gray-800 dark:border-gray-600' : 'border-primary bg-primary/5'}
            `}>
              {uploadState === 'idle' ? (
                <>
                  <div className="h-16 w-16 bg-primary/10 rounded-full flex items-center justify-center mb-4">
                    <UploadCloud className="h-8 w-8 text-primary" />
                  </div>
                  <h3 className="text-lg font-bold text-gray-900 dark:text-white">Upload Patient Records</h3>
                  <p className="text-sm text-gray-500 text-center mt-2 max-w-md">
                    Drag and drop PDF reports here. Documents are automatically encrypted, vectorized, and isolated to your clinical ID.
                  </p>
                  <button onClick={handleSimulatedUpload} className="mt-6 px-6 py-2.5 bg-primary text-white rounded-lg font-medium hover:bg-primary/90 transition-colors shadow-md shadow-primary/20">
                    Browse Files
                  </button>
                </>
              ) : (
                <div className="w-full max-w-md space-y-6">
                  <div className="text-center">
                    <h3 className="text-lg font-bold text-gray-900 dark:text-white">Processing Document...</h3>
                    <p className="text-sm text-primary font-medium mt-1">pgvector Initialization</p>
                  </div>
                  <div className="space-y-4 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-gray-200 before:to-transparent">
                    <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                      <div className="flex items-center justify-center w-10 h-10 rounded-full border-2 border-white bg-primary text-white shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2">
                        {uploadState !== 'uploading' ? <CheckCircle2 className="w-5 h-5"/> : <Loader2 className="w-5 h-5 animate-spin"/>}
                      </div>
                      <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] p-4 rounded-xl border border-gray-100 bg-white shadow-sm">
                        <div className={`font-bold ${uploadState === 'uploading' ? 'text-primary' : 'text-gray-900'}`}>Uploading PDF</div>
                      </div>
                    </div>
                    <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                      <div className={`flex items-center justify-center w-10 h-10 rounded-full border-2 border-white shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2
                        ${uploadState === 'uploading' ? 'bg-gray-200 text-gray-400' : uploadState === 'extracting' ? 'bg-secondary text-secondary-foreground' : 'bg-primary text-white'}`}>
                        {uploadState === 'extracting' ? <Loader2 className="w-5 h-5 animate-spin"/> : uploadState === 'uploading' ? <div className="w-3 h-3 bg-white rounded-full"/> : <CheckCircle2 className="w-5 h-5"/>}
                      </div>
                      <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] p-4 rounded-xl border border-gray-100 bg-white shadow-sm">
                        <div className={`font-bold ${uploadState === 'extracting' ? 'text-secondary-foreground' : 'text-gray-500'}`}>Celery Extraction</div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* --- ANALYTICS TAB --- */}
        {activeTab === 'analytics' && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 hover:border-primary/50 transition-colors">
                <div className="flex justify-between items-start">
                  <div>
                    <p className="text-sm font-medium text-gray-500">Secure Records</p>
                    <h3 className="text-3xl font-bold text-gray-900 dark:text-white mt-2">1,204</h3>
                  </div>
                  <div className="p-3 bg-primary/10 rounded-xl"><FileText className="h-6 w-6 text-primary" /></div>
                </div>
              </div>
              <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 hover:border-primary/50 transition-colors">
                <div className="flex justify-between items-start">
                  <div>
                    <p className="text-sm font-medium text-gray-500">Avg Faithfulness Score</p>
                    <h3 className="text-3xl font-bold text-primary mt-2">93.5%</h3>
                  </div>
                  <div className="p-3 bg-primary/10 rounded-xl"><Activity className="h-6 w-6 text-primary" /></div>
                </div>
              </div>
              <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl shadow-sm border border-secondary hover:border-secondary transition-colors relative overflow-hidden">
                <div className="absolute top-0 right-0 w-16 h-16 bg-secondary/20 rounded-bl-full" />
                <div className="flex justify-between items-start relative z-10">
                  <div>
                    <p className="text-sm font-medium text-gray-700 dark:text-gray-300">Critic Interventions</p>
                    <h3 className="text-3xl font-bold text-secondary-foreground dark:text-secondary mt-2">12</h3>
                    <p className="text-xs text-gray-500 mt-1">Hallucinations prevented</p>
                  </div>
                  <div className="p-3 bg-secondary/20 rounded-xl"><AlertTriangle className="h-6 w-6 text-secondary-foreground dark:text-secondary" /></div>
                </div>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700">
              <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-6">Dual-Agent Verification Trends</h3>
              <div className="h-72 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={faithfulnessData}>
                    <defs>
                      <linearGradient id="colorScore" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="hsl(var(--primary))" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="hsl(var(--primary))" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                    <XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} dy={10} />
                    <YAxis domain={[70, 100]} axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} dx={-10} />
                    <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} itemStyle={{ color: 'hsl(var(--primary))', fontWeight: 'bold' }} />
                    <Area type="monotone" dataKey="score" stroke="hsl(var(--primary))" strokeWidth={3} fillOpacity={1} fill="url(#colorScore)" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        )}

      </main>
    </div>
  );
}
